default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: postgres
  password: pgsqldocker
  host: localhost
  port: 5433

development:
  <<: *default
  database: ieat_development

test:
  <<: *default
  database: ieat_test

production:
  <<: *default
  database: ieat_production
